Añadir task y mostrar task usando localStorage
FundacioEsplaiJava2024/ToDoList-grupo-1 pull request #24
Opened 2024-06-17 10:59 UTC by rvst312

primero lo guardamos en localStorage y después recuperamos los datos desde "Lists" los transformamos en Json y les hacemos un map para mostrarlos pasándolo como prop de "Listtem"

2024-06-17 11:00 UTC, Davidvamosfull approved these changes
Resuelto

2024-06-17 11:01 UTC, AngelCorral0 approved these changes
ok

2024-06-18 07:15 UTC, SaraVictorFernandez commented
Con qué ticket está relacionado?

2024-06-18 08:13 UTC, SaraVictorFernandez requested changes

2024-06-18 08:13 UTC, SaraVictorFernandez commented on src/components/Modal.tsx
> +interface Task {
This is repeated. You should declare the interface task only once and import it when you need it

2024-06-18 08:13 UTC, SaraVictorFernandez commented on src/components/AddButton.tsx
> +        window.location.reload();
This is a hack. React can handle state without reloading the window each time you need to change anything

2024-06-18 08:13 UTC, SaraVictorFernandez commented on src/components/Lists.tsx
> +    localStorage.setItem("tasks", JSON.stringify(updatedData));
here, you handle the save to local storage without reloading the window (as it should, this is the correct approach)

2024-06-20 22:22 UTC, closed without merging