Añadimos nuevo componente Modal.tsx y el componente Lists guardar datos
FundacioEsplaiJava2024/ToDoList-grupo-1 pull request #31
Opened 2024-06-27 11:06 UTC by Davidvamosfull

- Añadimos nuevo componente y la funcionalidad de Modal.tsx
- El componente Lists se pueda guardar los datos dentro del LocalStorage

2024-06-27 11:10 UTC, rvst312 approved these changes

2024-06-27 11:19 UTC, SaraVictorFernandez requested changes

2024-06-27 11:19 UTC, SaraVictorFernandez commented on src/components/AddButton.tsx
> +interface Task {
Por qué lo definís aquí (y en cada sitio donde lo necesitáis) en vez de definirlo únicamente una vez en un fichero y luego importarlo?

2024-06-27 11:19 UTC, SaraVictorFernandez commented on src/components/Modal.tsx
> +interface Task {
Esta definición ya la he visto

2024-06-27 11:19 UTC, SaraVictorFernandez commented on src/components/AddButton.tsx
> +interface Task {
Este feedback creo que ya os lo había dado... revisad las pull request antes de pedirme que las revise

2024-06-27 11:19 UTC, SaraVictorFernandez commented on src/components/AddButton.tsx
> +            <Modal show={show} hideModal={hideModal} onSubmit={handleAddTask} />
Por cada botón estáis creando un modal. No sería mejor tener un único modal de edición/creación de tareas en la App y que el botón pidiese que se mostrara (pasando la info de la tarea)?

2024-06-27 11:30 UTC, Davidvamosfull commented on src/components/AddButton.tsx
> +interface Task {
Ya lo solucionamos en un version posterior

2024-06-27 11:30 UTC, Davidvamosfull commented on src/components/Modal.tsx
> +interface Task {
Lo mismo hemos arreglado en la antigua version

2024-06-27 11:32 UTC, Davidvamosfull commented on src/components/AddButton.tsx
> +            <Modal show={show} hideModal={hideModal} onSubmit={handleAddTask} />
En un principio pensamos que el modal fuese reutilizable, pero por diversas razones dicidimos que fuese componentes unicos.

2024-06-28 07:26 UTC, SaraVictorFernandez commented on src/components/AddButton.tsx
> +            <Modal show={show} hideModal={hideModal} onSubmit={handleAddTask} />
Qué razones?

2024-06-28 07:26 UTC, SaraVictorFernandez commented on src/components/AddButton.tsx
> +        window.location.reload();
el window.location.reload() lo solucionáis en un PR posterior?

2024-06-28 07:29 UTC, SaraVictorFernandez commented on src/components/Modal.tsx
> +interface Task {
ok, lo dejo pasar entonces porque hoy ya es la presentación. Lo veo en la siguiente PR

2024-06-28 07:36 UTC, Davidvamosfull commented on src/components/AddButton.tsx
> +        window.location.reload();
En el codigo de AddButton en ese linea solo que queremos que muestre el modal.tsx, pero en otra version tenemos otra modaledit.tsx, en que uno añade y otro edita, y pensamos que al tener dos modales serian mas comodo.

La parte de window.location.reload() ya lo solucionamos en la version posterior.

2024-06-28 07:52 UTC, SaraVictorFernandez commented on src/components/AddButton.tsx
> +        window.location.reload();
PD: Por favor, contesta cada parte en la conversación que toque, es más fácil entender de qué se está hablando en cada momento, cerrar una conversación y seguir con la otra, etc

2024-06-28 07:54 UTC, SaraVictorFernandez commented on src/components/AddButton.tsx
> +            <Modal show={show} hideModal={hideModal} onSubmit={handleAddTask} />
David: "En el codigo de AddButton en ese linea solo que queremos que muestre el modal.tsx, pero en otra version tenemos otra modaledit.tsx, en que uno añade y otro edita, y pensamos que al tener dos modales serian mas comodo."

Lo de tener modal.tsx y modaledit.tsx no tiene que ver con crear N modales (uno por cada botón) o 1 modal en la App.

2024-06-28 08:15 UTC, Davidvamosfull commented on src/components/AddButton.tsx
> +            <Modal show={show} hideModal={hideModal} onSubmit={handleAddTask} />
Para separar la logica en dos componentes diferentes.

2024-06-28 08:16 UTC, SaraVictorFernandez commented on src/components/AddButton.tsx
> +            <Modal show={show} hideModal={hideModal} onSubmit={handleAddTask} />
Vale, por qué lo instanciáis en cada botón?

2024-06-28 08:24 UTC, SaraVictorFernandez approved these changes

2024-06-28 08:44 UTC, AngelCorral0 approved these changes
ok

2024-06-28 08:44 UTC, merged