Declarar componentes y añadir librería estilos "RadixUI"
FundacioEsplaiJava2024/ToDoList-grupo-1 pull request #5
Opened 2024-06-10 08:54 UTC by rvst312

-Borrar css por defecto
-Declarar estructura de componentes 
-Añadir librería "RadixUI" para la interfaz
-Crear scss

2024-06-10 08:55 UTC, AngelCorral0 approved these changes
ok

2024-06-10 11:05 UTC, Daniela-RL commented
ook

2024-06-10 11:23 UTC, SaraVictorFernandez requested changes

2024-06-10 11:23 UTC, SaraVictorFernandez commented on src/components/Lists.tsx
Cada componente debería ir en su propio fichero

2024-06-10 11:23 UTC, SaraVictorFernandez commented on src/components/Lists.tsx
> +export function ItemList({ title, description }: ItemProps) {
El nombre del css es más acertado. En inglés, una Item List es la lista de items. Un List Item es un elemento de la lista. Este componente debería llamarse "ListItem", puesto que devuelve un item

2024-06-10 11:23 UTC, SaraVictorFernandez commented on src/components/Lists.tsx
> +      {data.map((item, index) => (
Usar el índice como key es una mala opcion, se deberían usar identificadores (el índice no identifica el elemento, puesto que se podrían borrar o añadir elementos de la lista y, por lo tanto, cambiar el índice).

Ver siguiente enlace: https://www.dhiwise.com/post/react-lists-and-keys-the-key-to-efficient-rendering

2024-06-11 07:38 UTC, rvst312 commented on src/components/Lists.tsx
> +export function ItemList({ title, description }: ItemProps) {
hemos cambiamos "ItemList" por "ListItem"

2024-06-11 07:39 UTC, rvst312 commented on src/components/Lists.tsx
se separaron los componentes en archivos independientes

2024-06-11 07:41 UTC, rvst312 commented on src/components/Lists.tsx
> +      {data.map((item, index) => (
añadimos un id único a cada task. Ahora la "key" recibe un "item.id" en lugar de usar el index

2024-06-14 07:51 UTC, SaraVictorFernandez approved these changes

2024-06-14 07:52 UTC, merged